# Generated by Django 2.2 on 2020-08-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_auto_20200730_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'Forming'), ('STP', 'In progress'), ('PD', 'Paid'), ('PRD', 'Processing'), ('RDY', 'Ready for pickup'), ('CNC', 'Canceled')], default='FM', max_length=3, verbose_name='status'),
        ),
    ]
