# Generated by Django 2.2 on 2020-07-21 10:12

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expiration',
            field=models.DateTimeField(default=authapp.models.get_expiration_date),
        ),
    ]
