# Generated by Django 2.2 on 2020-07-24 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200721_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tagline', models.CharField(blank=True, max_length=128, verbose_name='tags')),
                ('aboutMe', models.TextField(blank=True, max_length=512, verbose_name='about')),
                ('gender', models.CharField(blank=True, choices=[('M', 'M'), ('W', 'F')], max_length=1, verbose_name='gender')),
            ],
        ),
    ]
