# Generated by Django 2.2 on 2020-07-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200630_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_desc',
        ),
        migrations.AddField(
            model_name='product',
            name='level',
            field=models.CharField(blank=True, max_length=64, verbose_name='product level'),
        ),
    ]
